### ISSUE TITLE
Produce region mapping for subdivided parcellations

### ISSUE THREAD

**Issue by maedoc** [ins-amu/scripts#43]
This would be useful for computing areas per subparcel as well.

This info seems to be hiding in subparcel.m around lines 175-200 but I'm not too sure how the indices work there.

**Comment by timpx** [comment]
I actually have the code here to do just that, but did not committed it as I wanted to clean it a bit before.
The concept is to project the parcellation on the surface by a greedy algorithm, and then to correct the region mapping with functions (a bit modified) already available in scripts.

for the area, I think it's easy to compute once you got the region mapping

**Comment by maedoc** [comment]
Awesome, push it in a branch maybe?

**Comment by timpx** [comment]
done
