### ISSUE TITLE
Alternative parcellation strategies

### ISSUE THREAD

**Issue by maedoc** [ins-amu/scripts#44]
The use of FreeSurfer for parcellation was criticized in the vibration videoconference for a few reasons, such as uneven parcel areas, long geometry (as opposed to roughly circular), and lack of basis in underlying biology e.g. histology...

They proposed to make parcels based on the DWI directly, based on the fibers themselves.

If I understand correctly, the fiber tracking is independent of parcellation, and the generation of connectivity and tract lenght matrices is obtained by applying a node label/parcel image to the tracts (counting number of tracts for weights and average length). Is this correct?

So, if we had another node label/parcel image based DWI or whatever they propose, we'd generate another connectivity as they're asking for.

The problem for simulation enters when we consider how to obtain a regionmapping when the connectivity is not based on the cortical surface segmentation & parcellation FreeSurfer generates. Perhaps a nearest voxel-vertex approach could work. 

What do you think?

**Comment by timpx** [comment]
Added four other atlases (Destrieux, HCP-MMP, Yeo7. Yeo17). Other atlases are more complex to include. Many of them could come with SPM.
