### ISSUE TITLE
globa tractography option

### ISSUE THREAD

**Issue by timpx** [ins-amu/scripts#58]
http://community.mrtrix.org/t/sift2-after-global-tractography/499

**Comment by maedoc** [comment]
Did you actually try this or just include for completeness ?

**Comment by timpx** [comment]
Did not try, but I read about this, and the issue with global tractography is that it does not currently fit with anatomical constraints for fiber seeding/termination (ACT), so that while the reconstruction correctly fit the original signal, it does not guarantee the tracks have any meaning. See http://community.mrtrix.org/t/sift2-after-global-tractography/499/13. So I am closing for now

**Comment by timpx** [comment]
as a side note, they find a exponential distribution of track lengths in the paper (Christiaens et al, 2015, Fig. 11)
