### ISSUE TITLE
alternative bbregister registration method

### ISSUE THREAD

**Issue by timpx** [ins-amu/scripts#60]

**Comment by maedoc** [comment]
Denis has code for this.. or is that what you have in mind?

**Comment by timpx** [comment]
I meant this: https://github.com/ins-amu/scripts/blob/df74c8bb00a57c900ef688cb2063622d8294dc1b/main_surface.sh#L512-L538
and this:
https://github.com/ins-amu/scripts/blob/df74c8bb00a57c900ef688cb2063622d8294dc1b/main_surface.sh#L599-L632
