### ISSUE TITLE
Running docker container without Matlab

### ISSUE THREAD

**Issue by pedrocklein** [ins-amu/scripts#63]
Hi,

I am trying to run the pipeline in a Docker container but I am getting an error when it gets to the point where the script runs the subparcel.m script (main_surface.sh line 1108).

Is it possible to run this pipeline without having Matlab installed (in this case, using the MCR)? If so, what would be the needed changes to do to the Docker container in order to get this working?

Best,

**Comment by maedoc** [comment]
Would have to use the MATLAB Compiler and then install the MCR in the Docker image.  Do you have the license or not?

**Comment by pedrocklein** [comment]
Hi,

I don't have access to a Matlab license for this container, but I've installed the MCR according to the installation instructions for the version 0.3 of SCRIPTS. The idea would be compiling the .m files outside the docker container?

Best,

**Comment by timpx** [comment]
Hi, 
yes you would need to do that. I am sorry I did not do it for this version of SCRIPTS, but the idea was and is to replace this subparcellation algorithm with a Python equivalent to get rid of all Matlab dependencies. I can prioritize it if you need it. In the mean time, I can commit a compiled version of the Matlab code if you want (I think you need Matlab to compile the code). Let me know

**Comment by pedrocklein** [comment]
Hi,

It would be awesome if you could made available a compiled version of the Matlab dependencies, otherwise I would be stuck at this point on the pipeline. 

I considered translating the Matlab scripts to Python manually, but I am not very familiar to Matlab syntax, so this would take a considerable amount of time. However, I still not discarded this idea, so please let me know if I could be of any help with this.

Thank you very much!

**Comment by timpx** [comment]
ok, I will do that. Just to let you know, you can still run SCRIPTS completely without computing subparcellations by setting `export K_LIST=""` in the config file.

**Comment by timpx** [comment]
I just added the compiled version, let me know if it works for you

**Comment by maedoc** [comment]
@pedrocklein can you send a PR for MCR in Dockerfile?

**Comment by pedrocklein** [comment]
Hi @maedoc, PR would be a pull request? If so, how do I send it?

**Comment by maedoc** [comment]
Yes, you can fork the repo, make a branch, edit the code, push and then click the New Pull Request button
