### ISSUE TITLE
tests with HCP data

### ISSUE THREAD

**Issue by guiguiw** [ins-amu/scripts#64]
Hi，I am new here. I want to run the test in scripts/tests. I find "first run a subject on either your data or with HCP data with the default configuration file", I have the T1 and dMRI data of HCP, but I don't know how to run a subject data with the default configuration file. Is that mean I need to run scripts/tests/test_test.sh first? Then run "bash tests/test_pipeline.sh -c path_to_config_file", path_to_config_file means the location of scripts/example_config.sh?
Thanks.

**Comment by timpx** [comment]
Hi guiguiw, you don't need to run scripts/tests/test_test.sh, this is just for testing purpose. Assuming you properly set up your directories, you need to run:
```bash
bash main_surface.sh -c path_to_config_file
```
You should update your config_file accordingly, in particular setting the HCP option to "yes".
I apologize for the documentation which is old and need to be updated, hopefully I can do that very soon. 
Let me know if it works
