### ISSUE TITLE
Error with libgsl

### ISSUE THREAD

**Issue by jjt20** [ins-amu/scripts#67]
Hi,

I've gotten the following error in the decimation step of the pipeline:

./remesher/cmdremesher/cmdremesher: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory

The command given in the installation instructions, sudo apt-get install g++ libgsl0-dev, results in the installation of libgsl-dev instead of libgsl0-dev. It seems as though this shouldn't cause issues, since from what I've read libgsl0 is a virtual package in libgsl, but I'm not sure what else the issue could be.

Best,
Joe

**Comment by jjt20** [comment]
The issue was resolved by running the following command prior to running the pipeline:
sudo ln -s `find /usr -name libgsl.so`{,.0}

**Comment by timpx** [comment]
I got the same issue, I will add it to installation instructions
